name: Run PSScriptAnalyzer

on: [push, pull_request, workflow_dispatch]

jobs:
  analyze:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748 # 2.3.4
      - run: pwsh ./powershell-script-analyzer.ps1
