name: Run PSScriptAnalyzer

on: [push, pull_request, workflow_dispatch]

jobs:
  analyze:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # 2.3.4
      - run: pwsh ./powershell-script-analyzer.ps1
