name: Run PSScriptAnalyzer

on: [push, pull_request, workflow_dispatch]

jobs:
  analyze:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # 2.3.4
      - run: pwsh ./powershell-script-analyzer.ps1
