name: Run PSScriptAnalyzer

on: [push, pull_request, workflow_dispatch]

jobs:
  analyze:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # 3.2.0
      - run: pwsh ./powershell-script-analyzer.ps1
