name: Run PSScriptAnalyzer

on: [push, pull_request, workflow_dispatch]

jobs:
  analyze:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # 3.3.0
      - run: pwsh ./powershell-script-analyzer.ps1
