name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # 3.3.0
      - uses: actions/setup-dotnet@51f68377c181a79065c61bd492bd49be4575c439 # 1.7.2
        with:
          dotnet-version: "5.0.102"
      - run: pwsh ./test.ps1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
