name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # 2.3.4
      - uses: actions/setup-dotnet@4d4a70f4a5b2a5a5329f13be4ac933f2c9206ac0 # 1.7.2
        with:
          dotnet-version: "5.0.102"
      - run: pwsh ./test.ps1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
